/** Chave em hall_of_fame_cache → chave da UI (HallCategory.key). */
export const CACHE_CATEGORY_TO_HALL_KEY: Record<string, string> = {
  top_scorers: "goals",
  top_assists: "assists",
  goal_participation: "goal_participation",
  most_matches: "matches",
  most_wins: "wins",
  most_titles: "athlete_titles",
  most_finals: "athlete_finals",
  most_awards: "athlete_awards",
  most_totw: "totw",
  most_motw: "motw",
  most_motm: "motm",
  most_tots: "tots",
  most_hat_tricks: "hat_tricks",
  most_pokers: "pokers",
  most_goals_in_match: "goals_in_match",
  best_penalty_rate: "penalty_rate",
  best_shootout_rate: "shootout_rate",
  gk_clean_sheets: "gk_clean_sheets",
  gk_penalty_saves: "gk_penalty_saves",
  gk_shootout_saves: "gk_shootout_saves",
  team_titles: "team_titles",
  team_wins: "team_wins",
  team_goals: "team_goals",
  team_clean_sheets: "mais_cleansheets",
  team_unbeaten: "sequencia_invicto",
  team_win_streak: "sequencia_vitorias",
  maior_goleada: "maior_goleada",
};

export const HALL_KEY_TO_CACHE_CATEGORY: Record<string, string> = Object.fromEntries(
  Object.entries(CACHE_CATEGORY_TO_HALL_KEY).map(([cache, hall]) => [hall, cache]),
);

export const HALL_CACHE_CATEGORIES = [
  "top_scorers",
  "top_assists",
  "goal_participation",
  "most_matches",
  "most_wins",
  "most_titles",
  "most_finals",
  "most_awards",
  "most_totw",
  "most_motw",
  "most_motm",
  "most_tots",
  "most_hat_tricks",
  "most_pokers",
  "most_goals_in_match",
  "best_penalty_rate",
  "best_shootout_rate",
  "gk_clean_sheets",
  "gk_penalty_saves",
  "gk_shootout_saves",
  "team_titles",
  "team_wins",
  "team_goals",
  "team_clean_sheets",
  "team_unbeaten",
  "team_win_streak",
] as const;
